### PR TITLE
Scrum 21 back login/register page

### PR DESCRIPTION
**Pull request by GytisPra**
- Implemented an invite code functionality so when registering it is required. 
- Fixed some minor front-end bugs so that errors are displayed correctly.

### CODE REVIEW

**Review by nobodiis — APPROVED** [review]
Good work! 😘

**Comment by gedvilad** [comment]
Need verifications when user doesnt write anything into input box (register page), bet šjp tai mldc 😘❤️

**Review by gedvilad — APPROVED** [review]
Need verifications when user doesnt write anything into input box (register page), bet šjp tai mldc 😘❤️

**Review by K4R0L15 — COMMENTED** [review]
Viskas tvarkoje

**Pull request merged**
