### PR TITLE
Login/Register front end ir questioner front-end

### PR DESCRIPTION
**Pull request by nobodiis**
Created a login/register page front-end design which will be changed in upcoming sprint.
Also created a questionnaire page which will be implemented into the dashboard as a pop up later into the next sprint.

### CODE REVIEW

**Comment by gedvilad** [comment]
Very beautiful 😍

**Review by gedvilad — APPROVED** [review]
Very beautiful 😍

**Review by GytisPra — APPROVED** [review]
Sutvarkyk conflicts ir tada all good

**Review by K4R0L15 — APPROVED** [review]
Viskas atrodo gerai

**Review by Makleris73 — APPROVED** [review]

**Pull request merged**
